const styles = {
	'.px-80': { paddingRight: '80px', paddingLeft: '80px' },
	'.px-sm-30': { padding: '0px 30px' },
	'.p-sm-24': { padding: '24px !important' },
	'.px-sm-24': { padding: '0px 24px !important' },
	'.pt-sm-24': { paddingTop: '24px !important' },
	'.pl-sm-24': { paddingLeft: '24px !important' },
	'.m-auto': { margin: 'auto !important' },
	'.mx-auto': { marginLeft: 'auto !important', marginRight: 'auto !important' },
	'.my-auto': { marginTop: 'auto !important', marginBottom: 'auto !important' },
	'.m-sm-30': { margin: '30px' },
	'.mb-sm-30': { marginBottom: '30px' },
	'.w-full': { width: '100%' },
	'.max-w-full': { maxWidth: '100% !important' },
	'.w-full-screen': { width: '100vw' },
	'.min-w-750': { minWidth: '750px' },
	'.max-w-770': { maxWidth: '770px' },
	'.h-full': { height: '100% !important' },
	'.h-full-screen': { height: '100vh' },
	'.h-150px': { height: '150px !important' },
	'.size-36': { height: '36px !important', width: '36px !important' },
	'.size-24': { height: '24px !important', width: '24px !important' }
};
